### ISSUE TITLE
NO Effect is working

### ISSUE THREAD

**Issue by bilz636** [akella/webgl-mouseover-effects#24]
HI, I had been looking for this effect. I followed your tutorial and implement the code exactly like you did but mine is not working. Even i downloaded your project from github and i open the step1.html file and only loading spinning icon. (i removed the loading icone) but no effect is working. Can you please have a look into this happen and guid me what i am missing? i am new newbie to webgl n threejs. Thank you 

Ref: https://tympanus.net/codrops/2020/04/14/interactive-webgl-hover-effects/

Ref https://tympanus.net/Tutorials/webgl-mouseover-effects/step1.html

**Comment by akella** [comment]
its hard to say, but if it didnt work there should be probably error in console, check the console and let me know.

**Comment by bilz636** [comment]
> its hard to say, but if it didnt work there should be probably error in console, check the console and let me know.

OKay, I guess my bad. I did not knew i had to run dependences which i am unfamilair with it. i thought its simple html, css , some javascript project. Sorry
