### ISSUE TITLE
Remove Brightness on Zoom

### ISSUE THREAD

**Issue by dennisregalado** [akella/webgl-mouseover-effects#7]
<img width="476" alt="Screen Shot 2020-12-30 at 4 08 49 PM" src="https://user-images.githubusercontent.com/35279373/103383726-765acf00-4ab9-11eb-9280-8601275ff148.png">

Hey there! How can I go about removing the brightness / glow present on the Zoom type?

**Comment by akella** [comment]
you need to edit shaders
